spring.datasource.url=jdbc:sqlite:./data/tracker.db?busy_timeout=2000
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update